# Generated by Django 5.0.14 on 2025-06-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appImpulsoEsporte", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="tipo_conta",
            field=models.CharField(
                choices=[
                    ("jogador", "Jogador"),
                    ("patrocinador", "Patrocinador"),
                    ("equipe", "Equipe"),
                    ("admin", "Administrador"),
                    ("outro", "Outro"),
                ],
                default="atleta",
                max_length=20,
                verbose_name="Tipo de Conta",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("jogador", "Jogador"),
                    ("patrocinador", "Patrocinador"),
                    ("equipe", "Equipe"),
                    ("admin", "Administrador"),
                    ("outro", "Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
