# Generated by Django 5.0.14 on 2025-06-26 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appImpulsoEsporte", "0002_usuario_tipo_conta_alter_usuario_tipo_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="tipo_conta",
            field=models.CharField(
                choices=[
                    ("", "Selecione o tipo de conta"),
                    ("atleta", "Atleta"),
                    ("patrocinador", "Patrocinador"),
                    ("equipe", "Equipe"),
                    ("outro", "Outro"),
                ],
                default="atleta",
                max_length=20,
                verbose_name="Tipo de Conta",
            ),
        ),
        migrations.AlterField(
            model_name="usuario",
            name="tipo_usuario",
            field=models.CharField(
                choices=[
                    ("", "Selecione o tipo de conta"),
                    ("atleta", "Atleta"),
                    ("patrocinador", "Patrocinador"),
                    ("equipe", "Equipe"),
                    ("outro", "Outro"),
                ],
                max_length=20,
            ),
        ),
    ]
