# Generated by Django 5.0.14 on 2025-06-26 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appImpulsoEsporte",
            "0003_alter_usuario_tipo_conta_alter_usuario_tipo_usuario",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patrocinador",
            name="aberto_para_oportunidades",
            field=models.BooleanField(
                default=True,
                help_text="Indica se o patrocinador está disponível para novas parcerias",
                verbose_name="Aberto para oportunidades de patrocínio",
            ),
        ),
        migrations.AddField(
            model_name="patrocinador",
            name="descricao",
            field=models.TextField(
                blank=True,
                help_text="Breve descrição sobre a empresa e o que oferece",
                null=True,
                verbose_name="Descrição da empresa",
            ),
        ),
    ]
