# Generated by Django 5.0.14 on 2025-06-27 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appImpulsoEsporte", "0004_patrocinador_aberto_para_oportunidades_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipeDisponivel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nome",
                    models.CharField(max_length=100, verbose_name="Nome da Equipe"),
                ),
                (
                    "modalidade",
                    models.CharField(
                        max_length=50, verbose_name="Modalidade Esportiva"
                    ),
                ),
                ("cidade", models.CharField(max_length=100, verbose_name="Cidade")),
                (
                    "descricao",
                    models.TextField(
                        blank=True,
                        help_text="Informações sobre a equipe, objetivos e requisitos",
                        null=True,
                        verbose_name="Descrição da equipe",
                    ),
                ),
                (
                    "ano_fundacao",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Ano de Fundação"
                    ),
                ),
                (
                    "numero_atletas",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Número atual de atletas"
                    ),
                ),
                (
                    "aberta_para_atletas",
                    models.BooleanField(
                        default=True,
                        help_text="Indica se a equipe está recrutando novos membros",
                        verbose_name="Aberta para novos atletas",
                    ),
                ),
                (
                    "contato_responsavel",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Responsável pelo contato",
                    ),
                ),
                (
                    "email_contato",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email para contato",
                    ),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                ("data_atualizacao", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Equipe Disponível",
                "verbose_name_plural": "Equipes Disponíveis",
                "ordering": ["-data_atualizacao"],
            },
        ),
    ]
