# Generated by Django 5.0.14 on 2025-07-03 22:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appImpulsoEsporte', '0005_equipedisponivel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equipe',
            old_name='nome_da_equipe',
            new_name='nome',
        ),
        migrations.AddField(
            model_name='equipe',
            name='localizacao',
            field=models.CharField(default=None, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipe',
            name='usuario',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipe', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='esporte',
            field=models.CharField(max_length=100),
        ),
    ]
