# Generated by Django 5.0.14 on 2025-07-07 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "appImpulsoEsporte",
            "0006_rename_nome_da_equipe_equipe_nome_equipe_localizacao_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="patrocinador",
            name="logo",
            field=models.ImageField(
                blank=True, null=True, upload_to="logos_patrocinadores/"
            ),
        ),
        migrations.AddField(
            model_name="patrocinador",
            name="site",
            field=models.URLField(
                blank=True, null=True, verbose_name="Site da empresa"
            ),
        ),
    ]
