# Generated by Django 5.0.14 on 2025-07-06 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appImpulsoEsporte', '0006_rename_nome_da_equipe_equipe_nome_equipe_localizacao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrocinador',
            name='aberto_para_oportunidades',
        ),
    ]
