# Generated by Django 5.0.14 on 2025-07-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appImpulsoEsporte', '0008_patrocinador_email_empresa_patrocinador_site_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patrocinador',
            name='email_empresa',
        ),
        migrations.AlterField(
            model_name='patrocinador',
            name='site_empresa',
            field=models.URLField(default='https://exemplo.com', help_text='Website oficial da empresa', verbose_name='Site da empresa'),
        ),
    ]
