# Generated by Django 5.0.14 on 2025-07-07 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appImpulsoEsporte", "0007_patrocinador_logo_patrocinador_site"),
        ("appImpulsoEsporte", "0009_remove_patrocinador_email_empresa_and_more"),
    ]

    operations = []
