# Generated by Django 5.0.14 on 2025-07-07 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appImpulsoEsporte", "0010_merge_20250707_1852"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="patrocinador",
            name="site_empresa",
        ),
        migrations.AlterField(
            model_name="patrocinador",
            name="site",
            field=models.URLField(
                blank=True,
                help_text="Website oficial da empresa",
                null=True,
                verbose_name="Site da empresa",
            ),
        ),
        migrations.CreateModel(
            name="Partida",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("horario", models.TimeField()),
                ("adversario", models.CharField(max_length=100)),
                ("local", models.CharField(max_length=100)),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partidas",
                        to="appImpulsoEsporte.equipe",
                    ),
                ),
            ],
        ),
    ]
