# Generated by Django 5.0.14 on 2025-07-11 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appImpulsoEsporte', '0011_remove_patrocinador_site_empresa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipedisponivel',
            name='aberta_para_atletas',
        ),
        migrations.CreateModel(
            name='Atleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicao', models.CharField(max_length=50)),
                ('idade', models.PositiveIntegerField()),
                ('equipe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appImpulsoEsporte.equipe')),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appImpulsoEsporte.esporte')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatrocinioAtleta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Atleta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appImpulsoEsporte.atleta')),
                ('patrocinador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appImpulsoEsporte.patrocinador')),
            ],
        ),
    ]
